### ISSUE TITLE
Add support for configuration Modules

### ISSUE THREAD

**Issue by cantremember** [cjimison/barrage#53]
add support for configuration to be broken up into Modules and imported into other Modules, so that complex configuration doesn't have to be one big honking blob of JSON

thanks!

**Comment by cjimison** [comment]
This is going to take a bit more work because the UI will have to be updated to support this.  For now I am going to backlog this request until we can work out the kinks in the current system.  Once the UI guys have cleaned up there bugs for R0.2 I will add this as the next major feature to the system.

**Comment by cantremember** [comment]
revoking Issue
